apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfthd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yfthd
  template:
    metadata:
      labels:
        app: yfthd
    spec:
      containers:
      - image: okteto.dev/yfthd:latest
        name: yfthd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4ce6aeff-4a68-40ea-93a8-befb7b2b3a8b"
        - name: Vless_Path
          value: "/yfuihyithd"
        - name: Vmess_UUID
          value: "4ce6aeff-4a68-40ea-93a8-befb7b2b3a8b"
        - name: Vmess_Path
          value: "/yfthd"
        - name: Share_Path
          value: "/v2link"
